server:
  port: 8090
  max-http-header-size: 10MB

spring:
  application:
    name: ocr-ft
  redis:
    host: redis服务器ip
    port: redis端口
    password: redis密码
    database: redis数据库id，默认为0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  client:
    service-url:
      defaultZone: eureka地址

temp-dir: ./temp/ # 存放临时图片的文件夹目录
