server:
  port: 8910
  max-http-header-size: 10MB
#  servlet:
#    context-path: /${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true

spring:
  application:
    name: consumer-ft

feign:
  hystrix:
    enabled: true
