server:
  port: 8800
  max-http-header-size: 10MB

spring:
  application:
    name: api
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  client:
    service-url:
      defaultZone: http://47.106.252.41:8761/eureka/
zuul:
  routes:
    ocrft:
      path: /api/**
      serviceId: consumer-ft
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000

ribbon:
  ConnectTimeout: 500 #连接超时
  ReadTimeout: 5000 #通信超时时间
  OkToRetryOnAllOperations: true #是否对所有操作重试
  MaxAutoRetriesNextServer: 2 #同一服务不同实例的重试次数
  MaxAutoRetries: 1 #同一实例的重试次数

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #熔断超时时长
