server:
  port: 8910
  max-http-header-size: 10MB
#  servlet:
#    context-path: /${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  client:
    service-url:
      defaultZone: http://desktop-h4ms7er:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: consumer-ft
  rabbitmq:
    host: 47.106.252.41
    port: 5672
    username: rabbit
    password: 123456

feign:
  hystrix:
    enabled: true
