server:
  port: 8800
  max-http-header-size: 10MB

spring:
  application:
    name: api
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  client:
    service-url:
      defaultZone: http://47.106.252.41:8761/eureka/
zuul:
  routes:
    ocrft:
      path: /ocrft/**
      serviceId: consumer-ft
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
