server:
  port: 8900
  max-http-header-size: 10MB

spring:
  application:
    name: provider-ft
  redis:
    host: 47.106.252.41
    port: 6379
    password: tcl654321.
    database: 0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  client:
    service-url:
      defaultZone: http://47.106.252.41:8761/eureka/

capacity: 4

save-dir: ./capture/
